import {IDictionary} from '../../../core/app-core';
import {AbstractLocalizationRepository} from '../abstract/abstract-localization-repository';
import {Injectable} from '@angular/core';

@Injectable()
export class MockLocalizationRepository extends AbstractLocalizationRepository {
  private _mockLocalizationStore: IDictionary<Array<ILocalization>> = {};

  constructor() {
    super();
    // Глобальные месседжи и проч. локализумые строки
    this._mockLocalizationStore['App'] = [
      { tagName:'msgError', lang:1, text:'Ошибка'},
      { tagName:'msgError', lang:2, text:'Помилка'},
      { tagName:'msgError', lang:3, text:'Error'},
      { tagName:'msgErrorEncountered', lang:1, text:'Возникла ошибка'},
      { tagName:'msgErrorEncountered', lang:2, text:'Сталася помилка'},
      { tagName:'msgErrorEncountered', lang:3, text:'There was an error'}
    ];

    this._mockLocalizationStore['FoxApp'] = [
      { tagName:'MainMenu', lang:1, text:'Меню'},
      { tagName:'MainMenu', lang:2, text:'Меню'},
      { tagName:'MainMenu', lang:3, text:'Menu'},
      { tagName:'InfoMenu', lang:1, text:'Информация'},
      { tagName:'InfoMenu', lang:2, text:'Інформація'},
      { tagName:'InfoMenu', lang:3, text:'Information'},
      { tagName:'OutApp', lang:1, text:'Выйти'},
      { tagName:'OutApp', lang:2, text:'Вийти'},
      { tagName:'OutApp', lang:3, text:'Log off'},
      { tagName:'Home', lang:1, text:'Главная'},
      { tagName:'Home', lang:2, text:'Головна'},
      { tagName:'Home', lang:3, text:'Home'},
      { tagName:'Categories', lang:1, text:'Категории'},
      { tagName:'Categories', lang:2, text:'Категорії'},
      { tagName:'Categories', lang:3, text:'Categories'},
      { tagName:'Account', lang:1, text:'Профиль'},
      { tagName:'Account', lang:2, text:'Профіль'},
      { tagName:'Account', lang:3, text:'Profile'},
      { tagName:'Map', lang:1, text:'Магазины'},
      { tagName:'Map', lang:2, text:'Магазини'},
      { tagName:'Map', lang:3, text:'Stores'},
      { tagName:'Actions', lang:1, text:'Акции'},
      { tagName:'Actions', lang:2, text:'Акції'},
      { tagName:'Actions', lang:3, text:'Promotion'},
      { tagName:'About', lang:1, text:'О нас'},
      { tagName:'About', lang:2, text:'Про нас'},
      { tagName:'About', lang:3, text:'About us'},
      { tagName:'Support', lang:1, text:'Поддержка'},
      { tagName:'Support', lang:2, text:'Підтримка'},
      { tagName:'Support', lang:3, text:'Support'},
      { tagName:'FoxOnFB', lang:1, text:'Фокстрот на Facebook'},
      { tagName:'FoxOnFB', lang:2, text:'Фокстрот на Facebook'},
      { tagName:'FoxOnFB', lang:3, text:'Foxtrot on Facebook'},
      { tagName:'Cancel', lang:1, text:'ОТМЕНИТЬ'},
      { tagName:'Cancel', lang:2, text:'СКАСУВАТИ'},
      { tagName:'Cancel', lang:3, text:'CANCEL'},
      { tagName:'NoveltyTitle', lang:1, text:'Новый товар в Фокстрот!'},
      { tagName:'NoveltyTitle', lang:2, text:'Новий товар у Фокстрот!'},
      { tagName:'NoveltyTitle', lang:3, text:'New product in Foxtrot!'},
      { tagName:'NoveltyMessage', lang:1, text:'Хотите взглянуть?'},
      { tagName:'NoveltyMessage', lang:2, text:'Бажаєте переглянути?'},
      { tagName:'NoveltyMessage', lang:3, text:'Do you want to check it?'},
      { tagName:'PromoTitle', lang:1, text:'Новая акция в Фокстрот!'},
      { tagName:'PromoTitle', lang:2, text:'Нова акція у Фокстрот!'},
      { tagName:'PromoTitle', lang:3, text:'New promotion in Foxtrot!'},
      { tagName:'PromoMessage', lang:1, text:'Хотите взглянуть?'},
      { tagName:'PromoMessage', lang:2, text:'Бажаєте переглянути?'},
      { tagName:'PromoMessage', lang:3, text:'Do you want to check it?'},
      { tagName:'PromocodeTitle', lang:1, text:'Проверьте свою корзину'},
      { tagName:'PromocodeTitle', lang:2, text:'Перевірте свій кошик'},
      { tagName:'PromocodeTitle', lang:3, text:'Check your cart'},
      { tagName:'PromocodeMessage', lang:1, text:'Мы добавили скидку к Вашему заказу'},
      { tagName:'PromocodeMessage', lang:2, text:'Ми додали знижку до Вашого замовлення'},
      { tagName:'PromocodeMessage', lang:3, text:'We have added a discount to your order'},
      { tagName:'OnlineMessage', lang:1, text:'Теперь Вы в сети через'},
      { tagName:'OnlineMessage', lang:2, text:'Тепер Ви в мережі через'},
      { tagName:'OnlineMessage', lang:3, text:'You are now online via'},
      { tagName:'OfflineMessage', lang:1, text:'Теперь Вы'},
      { tagName:'OfflineMessage', lang:2, text:'Тепер Ви'},
      { tagName:'OfflineMessage', lang:3, text:'You are now'},
    ];

    this._mockLocalizationStore['AccountPage'] = [
      { tagName:'ProfileChangedSuccessfully', lang:1, text:'Профайл успешно изменен'},
      { tagName:'ProfileChangedSuccessfully', lang:2, text:'Профайл успішно змінено'},
      { tagName:'ProfileChangedSuccessfully', lang:3, text:'Profile changed successfully'},
      { tagName:'Password', lang:1, text:'Пароль'},
      { tagName:'Password', lang:2, text:'Пароль'},
      { tagName:'Password', lang:3, text:'Password'},
      { tagName:'Name', lang:1, text:'Имя'},
      { tagName:'Name', lang:2, text:'Ім\'я'},
      { tagName:'Name', lang:3, text:'Name'},
      { tagName:'AppKey', lang:1, text:'Ключ'},
      { tagName:'AppKey', lang:2, text:'Ключ'},
      { tagName:'AppKey', lang:3, text:'AppKey'},
      { tagName:'Currency', lang:1, text:'Валюта'},
      { tagName:'Currency', lang:2, text:'Валюта'},
      { tagName:'Currency', lang:3, text:'Currency'},
      { tagName:'Language', lang:1, text:'Язык'},
      { tagName:'Language', lang:2, text:'Мова'},
      { tagName:'Language', lang:3, text:'Language'},
      { tagName:'Apply', lang:1, text:'Применить'},
      { tagName:'Apply', lang:2, text:'Застосувати'},
      { tagName:'Apply', lang:3, text:'Apply'},
      { tagName:'Logoff', lang:1, text:'Выйти'},
      { tagName:'Logoff', lang:2, text:'Вийти'},
      { tagName:'Logoff', lang:3, text:'Sign out'},
      { tagName:'RequiredField', lang:1, text:'Обязательное поле'},
      { tagName:'RequiredField', lang:2, text:'Обов\'язкове поле'},
      { tagName:'RequiredField', lang:3, text:'Required field'},
      { tagName:'WrongEMailFormat', lang:1, text:'Не правильный формат email адреса'},
      { tagName:'WrongEMailFormat', lang:2, text:'Не вірний формат email адреси'},
      { tagName:'WrongEMailFormat', lang:3, text:'Wrong email address format'},
      { tagName:'LengthNLT6', lang:1, text:'Значение должно быть не менее 6-ти символов'},
      { tagName:'LengthNLT6', lang:2, text:'Значення повинно бути не менше 6-ти символів'},
      { tagName:'LengthNLT6', lang:3, text:'Value length shouldn\'t be less than 6 symbols'},
      { tagName:'LengthNGT20', lang:1, text:'Значение должно быть не более 20-ти символов'},
      { tagName:'LengthNGT20', lang:2, text:'Значення повинно бути не більше 20-ти символів'},
      { tagName:'LengthNGT20', lang:3, text:'Value length shouldn\'t be grater than 20 symbols'},
      { tagName:'LengthNGT128', lang:1, text:'Значение должно быть не более 128-и символов'},
      { tagName:'LengthNGT128', lang:2, text:'Значення повинно бути не більше 128-и символів'},
      { tagName:'LengthNGT128', lang:3, text:'Value length shouldn\'t be grater than 128 symbols'},
    ];

    this._mockLocalizationStore['AccountMenuPage'] = [
      { tagName:'YourOrders', lang:1, text:'Ваши заказы'},
      { tagName:'YourOrders', lang:2, text:'Ваші замовлення'},
      { tagName:'YourOrders', lang:3, text:'Your orders'},
      { tagName:'YourFoxClubBalance', lang:1, text:'Ваш баланс пользователя ФоксКлуб'},
      { tagName:'YourFoxClubBalance', lang:2, text:'Ваш баланс користувача ФоксКлуб'},
      { tagName:'YourFoxClubBalance', lang:3, text:'Your FoxClub member\'s balance'},
      { tagName:'YourFoxClubCard', lang:1, text:'Ваша виртуальная карта ФоксКлуб'},
      { tagName:'YourFoxClubCard', lang:2, text:'Ваша віртуальна картка ФоксКлуб'},
      { tagName:'YourFoxClubCard', lang:3, text:'Your virtual FoxClub card'},
      { tagName:'Login&Security', lang:1, text:'Авторизация и Безопасность'},
      { tagName:'Login&Security', lang:2, text:'Авторизація і Безпека'},
      { tagName:'Login&Security', lang:3, text:'Login & Security'},
      { tagName:'ManageYourPlaces', lang:1, text:'Управление своими адресами'},
      { tagName:'ManageYourPlaces', lang:2, text:'Управління своїми адресами'},
      { tagName:'ManageYourPlaces', lang:3, text:'Manage your places'},
      { tagName:'Shopping', lang:1, text:'Покупки'},
      { tagName:'Shopping', lang:2, text:'Покупки'},
      { tagName:'Shopping', lang:3, text:'Shopping'},
      { tagName:'Settings', lang:1, text:'Настройки'},
      { tagName:'Settings', lang:2, text:'Налаштування'},
      { tagName:'Settings', lang:3, text:'Settings'},
    ];

    this._mockLocalizationStore['BarcodePage'] = [
    { tagName:'FoxClubCard', lang:1, text:'Виртуальная карта ФоксКлуб'},
    { tagName:'FoxClubCard', lang:2, text:'Віртуальна картка ФоксКлуб'},
    { tagName:'FoxClubCard', lang:3, text:'Virtual FoxClub card'},
    ];

    this._mockLocalizationStore['ActionsPage'] = [
      { tagName:'ActivePromotions', lang:1, text:'Активные акции'},
      { tagName:'ActivePromotions', lang:2, text:'Активні акції'},
      { tagName:'ActivePromotions', lang:3, text:'Active promotions'},
    ];

    this._mockLocalizationStore['BalancePage'] = [
      { tagName:'YourCurrentBonusBalance', lang:1, text:'Ваш актуальный баланс бонусов пользователя ФоксКлуб'},
      { tagName:'YourCurrentBonusBalance', lang:2, text:'Ваш актуальний баланс бонусів користувача ФоксКлуб'},
      { tagName:'YourCurrentBonusBalance', lang:3, text:'Your current FoxClub member\'s bonus balance'},
      { tagName:'Bonus', lang:1, text:'Бонус'},
      { tagName:'Bonus', lang:2, text:'Бонус'},
      { tagName:'Bonus', lang:3, text:'Bonus'},
      { tagName:'Only', lang:1, text:'Только'},
      { tagName:'Only', lang:2, text:'Тільки'},
      { tagName:'Only', lang:3, text:'Only'},
      { tagName:'DaysLeft', lang:1, text:'день(дней) осталось'},
      { tagName:'DaysLeft', lang:2, text:'день(днів) залишилось'},
      { tagName:'DaysLeft', lang:3, text:'day(s) left'},
      { tagName:'HurryUp', lang:1, text:'Поторопитесь'},
      { tagName:'HurryUp', lang:2, text:'Покваптесь'},
      { tagName:'HurryUp', lang:3, text:'Hurry up'},
      { tagName:'More', lang:1, text:'Больше'},
      { tagName:'More', lang:2, text:'Більше'},
      { tagName:'More', lang:3, text:'More'},
      { tagName:'Less', lang:1, text:'Меньше'},
      { tagName:'Less', lang:2, text:'Менше'},
      { tagName:'Less', lang:3, text:'Less'},
      { tagName:'ValidTill', lang:1, text:'Действителен до'},
      { tagName:'ValidTill', lang:2, text:'Дійсний до'},
      { tagName:'ValidTill', lang:3, text:'Valid till'},
      { tagName:'PromoBonus', lang:1, text:'Акционный бонус'},
      { tagName:'PromoBonus', lang:2, text:'Акційний бонус'},
      { tagName:'PromoBonus', lang:3, text:'Promo bonus'},
      { tagName:'Continue', lang:1, text:'Далее'},
      { tagName:'Continue', lang:2, text:'Далі'},
      { tagName:'Continue', lang:3, text:'Continue'},
    ];

    this._mockLocalizationStore['CartPage'] = [
      { tagName:'CartSubtotal', lang:1, text:'Сумма корзины'},
      { tagName:'CartSubtotal', lang:2, text:'Сума кошика'},
      { tagName:'CartSubtotal', lang:3, text:'Cart subtotal'},
      { tagName:'Items', lang:1, text:'товар(-а/-ов)'},
      { tagName:'Items', lang:2, text:'товар(-и/-ів)'},
      { tagName:'Items', lang:3, text:'item(s)'},
      { tagName:'ProceedToCheckout', lang:1, text:'К размещению заказа'},
      { tagName:'ProceedToCheckout', lang:2, text:'До розміщення замовлення'},
      { tagName:'ProceedToCheckout', lang:3, text:'Proceed to checkout'},
      { tagName:'ImportantMessages', lang:1, text:'Важные уведомление косательно товаров в Вашей корзине'},
      { tagName:'ImportantMessages', lang:2, text:'Важливі повідомлення стосовно товарів у Вашому кошику'},
      { tagName:'ImportantMessages', lang:3, text:'Important messages for items in your cart'},
      { tagName:'FreeShipping', lang:1, text:'БЕСПЛАТНАЯ доставка'},
      { tagName:'FreeShipping', lang:2, text:'БЕЗКОШТОВНА доставка'},
      { tagName:'FreeShipping', lang:3, text:'FREE shipping'},
      { tagName:'Only', lang:1, text:'Только'},
      { tagName:'Only', lang:2, text:'Тільки'},
      { tagName:'Only', lang:3, text:'Only'},
      { tagName:'Left', lang:1, text:'осталось'},
      { tagName:'Left', lang:2, text:'залишилось'},
      { tagName:'Left', lang:3, text:'left'},
      { tagName:'OrderNow', lang:1, text:'Заказать сейчас'},
      { tagName:'OrderNow', lang:2, text:'Замовити зараз'},
      { tagName:'OrderNow', lang:3, text:'Order now'},
      { tagName:'InStock', lang:1, text:'В наличии'},
      { tagName:'InStock', lang:2, text:'В наявності'},
      { tagName:'InStock', lang:3, text:'In Stock'},
      { tagName:'ShippedBy', lang:1, text:'Поставщик'},
      { tagName:'ShippedBy', lang:2, text:'Постачальник'},
      { tagName:'ShippedBy', lang:3, text:'Shipped by'},
      { tagName:'FreePickup', lang:1, text:'БЕСПЛАТНОЕ получение'},
      { tagName:'FreePickup', lang:2, text:'БЕЗКОШТОВНЕ отримання'},
      { tagName:'FreePickup', lang:3, text:'FREE pickup at'},
      { tagName:'Delete', lang:1, text:'Удалить'},
      { tagName:'Delete', lang:2, text:'Видалити'},
      { tagName:'Delete', lang:3, text:'Delete'},
      { tagName:'Quantity', lang:1, text:'Количество'},
      { tagName:'Quantity', lang:2, text:'Кількість'},
      { tagName:'Quantity', lang:3, text:'Quantity'},
      { tagName:'Qty', lang:1, text:'Кол-во'},
      { tagName:'Qty', lang:2, text:'Кіл-ть'},
      { tagName:'Qty', lang:3, text:'Qty'},
      { tagName:'CartAlertMessage', lang:1, text:'Некоторые товары в Вашем заказе нуждаются во внимании. Пожалуйста, проверьте заказ и попробуйте снова'},
      { tagName:'CartAlertMessage', lang:2, text:'Деякі товари з Вашого замовлення потребують уваги. Будь-ласка, перевірте замовлення і спробуйте знову'},
      { tagName:'CartAlertMessage', lang:3, text:'Some items in your order needs your attention. Please, review your order and try again'},
    ];

    this._mockLocalizationStore['ChangePasswordPage'] = [
      { tagName:'YourPass', lang:1, text:'Ваш пароль'},
      { tagName:'YourPass', lang:2, text:'Ваш пароль'},
      { tagName:'YourPass', lang:3, text:'Your password'},
      { tagName:'NewPass', lang:1, text:'Новый пароль'},
      { tagName:'NewPass', lang:2, text:'Новий пароль'},
      { tagName:'NewPass', lang:3, text:'New password'},
      { tagName:'Change', lang:1, text:'Изменить'},
      { tagName:'Change', lang:2, text:'Змінити'},
      { tagName:'Change', lang:3, text:'Change'},
    ];

    this._mockLocalizationStore['CheckoutPage'] = [
      { tagName:'PlaceYourOrder', lang:1, text:'Разместить заказ'},
      { tagName:'PlaceYourOrder', lang:2, text:'Розмістити замовлення'},
      { tagName:'PlaceYourOrder', lang:3, text:'Place your order'},
      { tagName:'OrderSummary', lang:1, text:'Итог заказа'},
      { tagName:'OrderSummary', lang:2, text:'Підсумок замовлення'},
      { tagName:'OrderSummary', lang:3, text:'Order summary'},
      { tagName:'OrderContainsErrors', lang:1, text:'Ваш заказ содержит ошибки. Пожалуйста, ознакомьтесь с деталями заказа ниже'},
      { tagName:'OrderContainsErrors', lang:2, text:'Ваше замовлення містить помилки. Будь-ласка, ознайомтесь із деталями замовлення нижче'},
      { tagName:'OrderContainsErrors', lang:3, text:'Your order contains errors. Please, review order details below'},
      { tagName:'ShippingTo', lang:1, text:'Доставка на'},
      { tagName:'ShippingTo', lang:2, text:'Доставка на'},
      { tagName:'ShippingTo', lang:3, text:'Shipping to'},
      { tagName:'Items', lang:1, text:'Товары'},
      { tagName:'Items', lang:2, text:'Товари'},
      { tagName:'Items', lang:3, text:'Items'},
      { tagName:'Shipping', lang:1, text:'Доставка'},
      { tagName:'Shipping', lang:2, text:'Доставка'},
      { tagName:'Shipping', lang:3, text:'Shipping'},
      { tagName:'OrderTotal', lang:1, text:'Сумма заказа'},
      { tagName:'OrderTotal', lang:2, text:'Сума замовлення'},
      { tagName:'OrderTotal', lang:3, text:'Order Total'},
      { tagName:'PromocodeDiscount', lang:1, text:'Скидка промокода'},
      { tagName:'PromocodeDiscount', lang:2, text:'Знижка промокоду'},
      { tagName:'PromocodeDiscount', lang:3, text:'Promocode discount'},
      { tagName:'Bonuses', lang:1, text:'Бонусы'},
      { tagName:'Bonuses', lang:2, text:'Бонуси'},
      { tagName:'Bonuses', lang:3, text:'Bonuses'},
      { tagName:'PromoBonuses', lang:1, text:'Акционные бонусы'},
      { tagName:'PromoBonuses', lang:2, text:'Акційні бонуси'},
      { tagName:'PromoBonuses', lang:3, text:'Promo bonuses'},
      { tagName:'GrandTotal', lang:1, text:'Окончательная стоимость'},
      { tagName:'GrandTotal', lang:2, text:'Кінцева вартість'},
      { tagName:'GrandTotal', lang:3, text:'Grand Total'},
      { tagName:'PaymentInfo', lang:1, text:'Информация об оплате'},
      { tagName:'PaymentInfo', lang:2, text:'Інформація про оплату'},
      { tagName:'PaymentInfo', lang:3, text:'Payment information'},
      { tagName:'PaymentMethod', lang:1, text:'Способ оплаты'},
      { tagName:'PaymentMethod', lang:2, text:'Спосіб оплати'},
      { tagName:'PaymentMethod', lang:3, text:'Payment method'},
      { tagName:'Shipment', lang:1, text:'Доставка'},
      { tagName:'Shipment', lang:2, text:'Доставка'},
      { tagName:'Shipment', lang:3, text:'Shipment'},
      { tagName:'Of', lang:1, text:'из'},
      { tagName:'Of', lang:2, text:'з'},
      { tagName:'Of', lang:3, text:'of'},
      { tagName:'ItemShippedFrom', lang:1, text:'Товар поставляется'},
      { tagName:'ItemShippedFrom', lang:2, text:'Товар постачається'},
      { tagName:'ItemShippedFrom', lang:3, text:'Item shipped from'},
      { tagName:'PickupAt', lang:1, text:'Получение в'},
      { tagName:'PickupAt', lang:2, text:'Отримання у'},
      { tagName:'PickupAt', lang:3, text:'Pickup at'},
      { tagName:'EstDeliveryDate', lang:1, text:'Предполагаемая дата доставки'},
      { tagName:'EstDeliveryDate', lang:2, text:'Передбачувана дата доставки'},
      { tagName:'EstDeliveryDate', lang:3, text:'Est. delivery date'},
      { tagName:'Quantity', lang:1, text:'Количество'},
      { tagName:'Quantity', lang:2, text:'Кількість'},
      { tagName:'Quantity', lang:3, text:'Quantity'},
      { tagName:'Qty', lang:1, text:'Кол-во'},
      { tagName:'Qty', lang:2, text:'Кіл-ть'},
      { tagName:'Qty', lang:3, text:'Qty'},
    ];

    this._mockLocalizationStore['CityPopoverPage'] = [
      { tagName:'FilterByCity', lang:1, text:'ФИЛЬТР ПО ГОРОДУ'},
      { tagName:'FilterByCity', lang:2, text:'ФІЛЬТР ПО МІСТУ'},
      { tagName:'FilterByCity', lang:3, text:'FILTER BY CITY'},
    ];

    this._mockLocalizationStore['CreditCalcPage'] = [
      { tagName:'PleaseWait', lang:1, text:'Пожалуйста, подождите'},
      { tagName:'PleaseWait', lang:2, text:'Будь-ласка, почекайте'},
      { tagName:'PleaseWait', lang:3, text:'Please, wait'},
      { tagName:'PrivatInstallments', lang:1, text:'Приват банк "Оплата частями"'},
      { tagName:'PrivatInstallments', lang:2, text:'Приват банк "Оплата частинами"'},
      { tagName:'PrivatInstallments', lang:3, text:'PrivatBank "Payment by installments"'},
      { tagName:'PrivatInstant', lang:1, text:'Приват банк "Мгновенная рассрочка"'},
      { tagName:'PrivatInstant', lang:2, text:'Приват банк "Миттєва розстрочка"'},
      { tagName:'PrivatInstant', lang:3, text:'PrivatBank "Instant Installment"'},
      { tagName:'GetForLoan', lang:1, text:'Взять в кредит'},
      { tagName:'GetForLoan', lang:2, text:'Взяти в кредит'},
      { tagName:'GetForLoan', lang:3, text:'Get it for a loan'},
      { tagName:'CartTotal', lang:1, text:'Сумма корзины'},
      { tagName:'CartTotal', lang:2, text:'Сума кошику'},
      { tagName:'CartTotal', lang:3, text:'Cart total'},
      { tagName:'LoanName', lang:1, text:'Название кредита'},
      { tagName:'LoanName', lang:2, text:'Назва кредиту'},
      { tagName:'LoanName', lang:3, text:'Loan name'},
      { tagName:'GracePeriod', lang:1, text:'Льготный период, мес'},
      { tagName:'GracePeriod', lang:2, text:'Льготний період, міс'},
      { tagName:'GracePeriod', lang:3, text:'Grace period, month'},
      { tagName:'LoanTerm', lang:1, text:'Срок кредита, мес'},
      { tagName:'LoanTerm', lang:2, text:'Термін кредиту, міс'},
      { tagName:'LoanTerm', lang:3, text:'Term of loan, month'},
      { tagName:'MonthlyPayment', lang:1, text:'Ежемесячный платёж'},
      { tagName:'MonthlyPayment', lang:2, text:'Щомісячний платіж'},
      { tagName:'MonthlyPayment', lang:3, text:'Monthly payment'},
      { tagName:'Continue', lang:1, text:'Далее'},
      { tagName:'Continue', lang:2, text:'Далі'},
      { tagName:'Continue', lang:3, text:'Continue'},
      { tagName:'LoadingContent', lang:1, text:'Пожалуйста, подождите...'},
      { tagName:'LoadingContent', lang:2, text:'Будь-ласка, зачекайте...'},
      { tagName:'LoadingContent', lang:3, text:'Please wait...'},
    ];

    this._mockLocalizationStore['EditShipAddressPage'] = [
      { tagName:'Error', lang:1, text:'Ошибка'},
      { tagName:'Error', lang:2, text:'Помилка'},
      { tagName:'Error', lang:3, text:'Error'},
      { tagName:'ReviewYourData', lang:1, text:'Пожалуйста, проверьте введённые данные'},
      { tagName:'ReviewYourData', lang:2, text:'Будь-ласка, перевірте введені дані'},
      { tagName:'ReviewYourData', lang:3, text:'Please, review your data!'},
      { tagName:'FirstLastName', lang:1, text:'Имя и фамилия'},
      { tagName:'FirstLastName', lang:2, text:'Ім\'я та прізвище'},
      { tagName:'FirstLastName', lang:3, text:'First and last name'},
      { tagName:'EnterFirstLastName', lang:1, text:'Пожалуйста, введите своё имя и фамилию'},
      { tagName:'EnterFirstLastName', lang:2, text:'Будь-ласка, введіть своє ім\'я та прізвище'},
      { tagName:'EnterFirstLastName', lang:3, text:'Please, enter your first and last name'},
      { tagName:'Street', lang:1, text:'Улица'},
      { tagName:'Street', lang:2, text:'Вулиця'},
      { tagName:'Street', lang:3, text:'Street'},
      { tagName:'EnterStreet', lang:1, text:'Пожалуйста, введите улицу'},
      { tagName:'EnterStreet', lang:2, text:'Будь-ласка, введіть вулицю'},
      { tagName:'EnterStreet', lang:3, text:'Please, enter your street'},
      { tagName:'BuildingAndApartment', lang:1, text:'Здание и квартира'},
      { tagName:'BuildingAndApartment', lang:2, text:'Будинок і квартира'},
      { tagName:'BuildingAndApartment', lang:3, text:'Building and apartment'},
      { tagName:'EnterBuildingAndApartment', lang:1, text:'Пожалуйста, введите здание и квартиру'},
      { tagName:'EnterBuildingAndApartment', lang:2, text:'Будь-ласка, введіть будинок і квартиру'},
      { tagName:'EnterBuildingAndApartment', lang:3, text:'Please, enter your building and apartment'},
      { tagName:'City', lang:1, text:'Город'},
      { tagName:'City', lang:2, text:'Місто'},
      { tagName:'City', lang:3, text:'City'},
      { tagName:'EnterCity', lang:1, text:'Пожалуйста, введите город'},
      { tagName:'EnterCity', lang:2, text:'Будь-ласка, введіть місто'},
      { tagName:'EnterCity', lang:3, text:'Please, enter your city'},
      { tagName:'Zip', lang:1, text:'Индекс'},
      { tagName:'Zip', lang:2, text:'Індекс'},
      { tagName:'Zip', lang:3, text:'Zip'},
      { tagName:'EnterZip', lang:1, text:'Пожалуйста, введите индекс'},
      { tagName:'EnterZip', lang:2, text:'Будь-ласка, введіть індекс'},
      { tagName:'EnterZip', lang:3, text:'Please, enter your zip'},
      { tagName:'Phone', lang:1, text:'Телефон'},
      { tagName:'Phone', lang:2, text:'Телефон'},
      { tagName:'Phone', lang:3, text:'Phone'},
      { tagName:'EnterPhone', lang:1, text:'Пожалуйста, введите номер телефона'},
      { tagName:'EnterPhone', lang:2, text:'Будь-ласка, введіть номер телефону'},
      { tagName:'EnterPhone', lang:3, text:'Please, enter your phone number'},
      { tagName:'PleaseSelectCountry', lang:1, text:'Пожалуйста, выберите страну'},
      { tagName:'PleaseSelectCountry', lang:2, text:'Будь-ласка, оберіть країну'},
      { tagName:'PleaseSelectCountry', lang:3, text:'Please, select country'},
      { tagName:'SelectCountry', lang:1, text:'Выберите страну'},
      { tagName:'SelectCountry', lang:2, text:'Виберіть країну'},
      { tagName:'SelectCountry', lang:3, text:'Select country'},
      { tagName:'SaveThisAddress', lang:1, text:'Сохранить этот адрес'},
      { tagName:'SaveThisAddress', lang:2, text:'Зберегти цю адресу'},
      { tagName:'SaveThisAddress', lang:3, text:'Save this address'},
      { tagName:'DeliverToThisAddress', lang:1, text:'Доставить по этому адресу'},
      { tagName:'DeliverToThisAddress', lang:2, text:'Доставити за цією адресою'},
      { tagName:'DeliverToThisAddress', lang:3, text:'Deliver to this address'},
    ];

    this._mockLocalizationStore['FavoriteStoresPage'] = [
      { tagName:'SelectFavStore', lang:1, text:'Выберите избранный магазин'},
      { tagName:'SelectFavStore', lang:2, text:'Виберіть обрану крамницю'},
      { tagName:'SelectFavStore', lang:3, text:'Select a favorite store'},
      { tagName:'ShowOnMap', lang:1, text:'Показать на карте'},
      { tagName:'ShowOnMap', lang:2, text:'Показати на карті'},
      { tagName:'ShowOnMap', lang:3, text:'Show on map'},
      { tagName:'Reviews', lang:1, text:'Отзывы'},
      { tagName:'Reviews', lang:2, text:'Відгуки'},
      { tagName:'Reviews', lang:3, text:'Reviews'},
      { tagName:'WriteReview', lang:1, text:'Написать отзыв'},
      { tagName:'WriteReview', lang:2, text:'Написати відгук'},
      { tagName:'WriteReview', lang:3, text:'Write review'},
      { tagName:'NoFavStoresYet', lang:1, text:'Вы пока не имеете избранных магазинов'},
      { tagName:'NoFavStoresYet', lang:2, text:'Ви поки не маєте обраних крамниць'},
      { tagName:'NoFavStoresYet', lang:3, text:'You have no favorite stores yet'},
      { tagName:'OrLoading', lang:1, text:'Или они ещё загружаются'},
      { tagName:'OrLoading', lang:2, text:'Або вони ще завантажуються'},
      { tagName:'OrLoading', lang:3, text:'Or they are loading'},
      { tagName:'AlertTitle', lang:1, text:'Подтверждение'},
      { tagName:'AlertTitle', lang:2, text:'Підтвердження'},
      { tagName:'AlertTitle', lang:3, text:'Confirmation'},
      { tagName:'AlertMessage', lang:1, text:'Вы уверены, что хотите удалить этот магазин из своих избранных магазинов?'},
      { tagName:'AlertMessage', lang:2, text:'Ви впевнені, що бажаєте видалити цю крамницю зі своїх обраних крамниць?'},
      { tagName:'AlertMessage', lang:3, text:'Are you sure you want to delete this store from your favorite stores?'},
      { tagName:'Cancel', lang:1, text:'Отменить'},
      { tagName:'Cancel', lang:2, text:'Відмінити'},
      { tagName:'Cancel', lang:3, text:'Cancel'},
    ];

    this._mockLocalizationStore['FilterPopoverPage'] = [
      { tagName:'Filter', lang:1, text:'ФИЛЬТР'},
      { tagName:'Filter', lang:2, text:'ФІЛЬТР'},
      { tagName:'Filter', lang:3, text:'FILTER'},
      { tagName:'ClearAll', lang:1, text:'Очистить всё'},
      { tagName:'ClearAll', lang:2, text:'Стерти все'},
      { tagName:'ClearAll', lang:3, text:'Clear all'},
      { tagName:'Relevance', lang:1, text:'Релевантность'},
      { tagName:'Relevance', lang:2, text:'Релевантність'},
      { tagName:'Relevance', lang:3, text:'Relevance'},
      { tagName:'Price: Low to High', lang:1, text:'Цена: от Дешевых к Дорогим'},
      { tagName:'Price: Low to High', lang:2, text:'Ціна: від Дешевих до Дорогих'},
      { tagName:'Price: Low to High', lang:3, text:'Price: Low to High'},
      { tagName:'Price: High to Low', lang:1, text:'Цена: от Дорогих к Дешевым'},
      { tagName:'Price: High to Low', lang:2, text:'Ціна: від Дорогих до Дешевих'},
      { tagName:'Price: High to Low', lang:3, text:'Price: High to Low'},
      { tagName:'Rating', lang:1, text:'Рейтинг'},
      { tagName:'Rating', lang:2, text:'Рейтинг'},
      { tagName:'Rating', lang:3, text:'Rating'},
      { tagName:'Sort', lang:1, text:'Сортировать'},
      { tagName:'Sort', lang:2, text:'Сортувати'},
      { tagName:'Sort', lang:3, text:'Sort'},
      { tagName:'Brand', lang:1, text:'Бренд'},
      { tagName:'Brand', lang:2, text:'Бренд'},
      { tagName:'Brand', lang:3, text:'Brand'},
      { tagName:'Number of SIM', lang:1, text:'Количество SIM'},
      { tagName:'Number of SIM', lang:2, text:'Кількість SIM'},
      { tagName:'Number of SIM', lang:3, text:'Number of SIM'},
      { tagName:'Built-in memory', lang:1, text:'Встроенная память'},
      { tagName:'Built-in memory', lang:2, text:'Вмонтована пам\'ять'},
      { tagName:'Built-in memory', lang:3, text:'Built-in memory'},
      { tagName:'Diagonal of display', lang:1, text:'Диагональ дисплея'},
      { tagName:'Diagonal of display', lang:2, text:'Діагональ дисплею'},
      { tagName:'Diagonal of display', lang:3, text:'Diagonal of display'},
      { tagName:'Type of power plug', lang:1, text:'Тип сетевой вилки'},
      { tagName:'Type of power plug', lang:2, text:'Тип мережевої вилки'},
      { tagName:'Type of power plug', lang:3, text:'Type of power plug'},
    ];

    this._mockLocalizationStore['ForgotPasswordPage'] = [
      { tagName:'EnterEmail', lang:1, text:'Введите Ваш email'},
      { tagName:'EnterEmail', lang:2, text:'Введіть Ваш email'},
      { tagName:'EnterEmail', lang:3, text:'Enter your email'},
      { tagName:'Clear', lang:1, text:'Сбросить'},
      { tagName:'Clear', lang:2, text:'Стерти'},
      { tagName:'Clear', lang:3, text:'Clear'},
    ];

    this._mockLocalizationStore['HomePage'] = [
      { tagName:'YourSearch', lang:1, text:'Ваш поиск'},
      { tagName:'YourSearch', lang:2, text:'Ваш пошук'},
      { tagName:'YourSearch', lang:3, text:'Your search'},
      { tagName:'DidNotMatch', lang:1, text:'не дал ни единого результата'},
      { tagName:'DidNotMatch', lang:2, text:'не дав жодного результату'},
      { tagName:'DidNotMatch', lang:3, text:'did not match any products'},
    ];

    this._mockLocalizationStore['ItemDetailPage'] = [
      { tagName:'InStock', lang:1, text:'В наличии'},
      { tagName:'InStock', lang:2, text:'В наявності'},
      { tagName:'InStock', lang:3, text:'In Stock'},
      { tagName:'SoldBy', lang:1, text:'Продавец'},
      { tagName:'SoldBy', lang:2, text:'Продавець'},
      { tagName:'SoldBy', lang:3, text:'Sold by'},
      { tagName:'AvailableForFreePickup', lang:1, text:'Доступно для бесплатного получения в'},
      { tagName:'AvailableForFreePickup', lang:2, text:'Доступно для безкоштовного отримання в'},
      { tagName:'AvailableForFreePickup', lang:3, text:'Available for FREE pickup in'},
      { tagName:'Places', lang:1, text:'местах'},
      { tagName:'Places', lang:2, text:'місцях'},
      { tagName:'Places', lang:3, text:'places'},
      { tagName:'FreePickupAt', lang:1, text:'Заберите бесплатно в'},
      { tagName:'FreePickupAt', lang:2, text:'Заберіть безкоштовно в'},
      { tagName:'FreePickupAt', lang:3, text:'FREE Pickup at'},
      { tagName:'Quantity', lang:1, text:'Количество'},
      { tagName:'Quantity', lang:2, text:'Кількість'},
      { tagName:'Quantity', lang:3, text:'Quantity'},
      { tagName:'Qty', lang:1, text:'Кол-во'},
      { tagName:'Qty', lang:2, text:'Кіл-ть'},
      { tagName:'Qty', lang:3, text:'Qty'},
      { tagName:'AddToCart', lang:1, text:'Добавить в корзину'},
      { tagName:'AddToCart', lang:2, text:'Додати до кошика'},
      { tagName:'AddToCart', lang:3, text:'Add to Cart'},
      { tagName:'GetForLoan', lang:1, text:'Взять в кредит'},
      { tagName:'GetForLoan', lang:2, text:'Взяти в кредит'},
      { tagName:'GetForLoan', lang:3, text:'Get it for a loan'},
      { tagName:'MoreQuotes', lang:1, text:'больше предложений от'},
      { tagName:'MoreQuotes', lang:2, text:'більше пропозицій від'},
      { tagName:'MoreQuotes', lang:3, text:'more quotes from'},
      { tagName:'AboutItem', lang:1, text:'Об этом товаре'},
      { tagName:'AboutItem', lang:2, text:'Про цей товар'},
      { tagName:'AboutItem', lang:3, text:'About this item'},
      { tagName:'CustomerReviews', lang:1, text:'Отзывы покупателей'},
      { tagName:'CustomerReviews', lang:2, text:'Відгуки покупців'},
      { tagName:'CustomerReviews', lang:3, text:'Customer reviews'},
      { tagName:'customerReviews', lang:1, text:'отзывов покупателей'},
      { tagName:'customerReviews', lang:2, text:'відгуків покупців'},
      { tagName:'customerReviews', lang:3, text:'customer reviews'},
      { tagName:'TopReviews', lang:1, text:'Лучшие отзывы'},
      { tagName:'TopReviews', lang:2, text:'Кращі відгуки'},
      { tagName:'TopReviews', lang:3, text:'Top reviews'},
      { tagName:'WriteReview', lang:1, text:'Оставить Отзыв'},
      { tagName:'WriteReview', lang:2, text:'Залишити Відгук'},
      { tagName:'WriteReview', lang:3, text:'Write a Review'},
    ];

    this._mockLocalizationStore['ItemQuotesPage'] = [
      { tagName:'FreeShipping', lang:1, text:'БЕСПЛАТНАЯ доставка'},
      { tagName:'FreeShipping', lang:2, text:'БЕЗКОШТОВНА доставка'},
      { tagName:'FreeShipping', lang:3, text:'FREE shipping'},
      { tagName:'Positive', lang:1, text:'положительных'},
      { tagName:'Positive', lang:2, text:'позитивних'},
      { tagName:'Positive', lang:3, text:'positive'},
      { tagName:'SellerRatings', lang:1, text:'рейтинг продавца'},
      { tagName:'SellerRatings', lang:2, text:'рейтинг продавця'},
      { tagName:'SellerRatings', lang:3, text:'seller ratings'},
      { tagName:'AddToCart', lang:1, text:'Добавить в корзину'},
      { tagName:'AddToCart', lang:2, text:'Додати до кошика'},
      { tagName:'AddToCart', lang:3, text:'Add to Cart'},
    ];

    this._mockLocalizationStore['ItemReviewWritePage'] = [
      { tagName:'YourReview', lang:1, text:'Ваш отзыв'},
      { tagName:'YourReview', lang:2, text:'Ваш відгук'},
      { tagName:'YourReview', lang:3, text:'Your review'},
      { tagName:'StoreByAddress', lang:1, text:'Магазин по адресу'},
      { tagName:'StoreByAddress', lang:2, text:'Крамниця за адресою'},
      { tagName:'StoreByAddress', lang:3, text:'Store by address'},
      { tagName:'WriteYourReview', lang:1, text:'Напишите свой отзыв здесь'},
      { tagName:'WriteYourReview', lang:2, text:'Напишіть свій відгук тут'},
      { tagName:'WriteYourReview', lang:3, text:'Write your review here'},
      { tagName:'Submit', lang:1, text:'Отправить'},
      { tagName:'Submit', lang:2, text:'Відправити'},
      { tagName:'Submit', lang:3, text:'Submit'},
    ];

    this._mockLocalizationStore['ItemReviewsPage'] = [
      { tagName:'CustomerReviews', lang:1, text:'Отзывы покупателей'},
      { tagName:'CustomerReviews', lang:2, text:'Відгуки покупців'},
      { tagName:'CustomerReviews', lang:3, text:'Customer reviews'},
      { tagName:'Of5Stars', lang:1, text:'из 5 звёзд'},
      { tagName:'Of5Stars', lang:2, text:'з 5 зірок'},
      { tagName:'Of5Stars', lang:3, text:'of 5 stars'},
      { tagName:'WriteReview', lang:1, text:'Оставить отзыв'},
      { tagName:'WriteReview', lang:2, text:'Залишити відгук'},
      { tagName:'WriteReview', lang:3, text:'Write a review'},
      { tagName:'ShowAnswers', lang:1, text:'Показать ответы'},
      { tagName:'ShowAnswers', lang:2, text:'Показати відповіді'},
      { tagName:'ShowAnswers', lang:3, text:'Show answers'},
    ];

    this._mockLocalizationStore['LoTrackItemPage'] = [
      { tagName:'TrackItem', lang:1, text:'Отслеживание заказа'},
      { tagName:'TrackItem', lang:2, text:'Відслідковування замовлення'},
      { tagName:'TrackItem', lang:3, text:'Track item'},
      { tagName:'TrackingNumber', lang:1, text:'№ заказа'},
      { tagName:'TrackingNumber', lang:2, text:'№ замовлення'},
      { tagName:'TrackingNumber', lang:3, text:'Tracking #'},
      { tagName:'DateTime', lang:1, text:'Дата/Время'},
      { tagName:'DateTime', lang:2, text:'Дата/Час'},
      { tagName:'DateTime', lang:3, text:'Date/Time'},
      { tagName:'TrackingStatus', lang:1, text:'Статус доставки'},
      { tagName:'TrackingStatus', lang:2, text:'Статус доставки'},
      { tagName:'TrackingStatus', lang:3, text:'Tracking status'},
    ];

    this._mockLocalizationStore['LoginPage'] = [
      { tagName:'RequiredField', lang:1, text:'Обязательное поле'},
      { tagName:'RequiredField', lang:2, text:'Обов\'язкове поле'},
      { tagName:'RequiredField', lang:3, text:'Required field'},
      { tagName:'WrongEMailFormat', lang:1, text:'Не правильный формат email адреса'},
      { tagName:'WrongEMailFormat', lang:2, text:'Не вірний формат email адреси'},
      { tagName:'WrongEMailFormat', lang:3, text:'Wrong email address format'},
      { tagName:'LengthNLT6', lang:1, text:'Значение должно быть не менее 6-ти символов'},
      { tagName:'LengthNLT6', lang:2, text:'Значення повинно бути не менше 6-ти символів'},
      { tagName:'LengthNLT6', lang:3, text:'Value length shouldn\'t be less than 6 symbols'},
      { tagName:'LengthNGT128', lang:1, text:'Значение должно быть не более 128-и символов'},
      { tagName:'LengthNGT128', lang:2, text:'Значення повинно бути не більше 128-и символів'},
      { tagName:'LengthNGT128', lang:3, text:'Value length shouldn\'t be grater than 128 symbols'},
      { tagName:'WrongLoginOrPass', lang:1, text:'Неверный email или пароль'},
      { tagName:'WrongLoginOrPass', lang:2, text:'Хибний email чи пароль'},
      { tagName:'WrongLoginOrPass', lang:3, text:'Wrong email or password'},
      { tagName:'Email', lang:1, text:'Электронная почта'},
      { tagName:'Email', lang:2, text:'Електронна пошта'},
      { tagName:'Email', lang:3, text:'Email'},
      { tagName:'Password', lang:1, text:'Пароль'},
      { tagName:'Password', lang:2, text:'Пароль'},
      { tagName:'Password', lang:3, text:'Password'},
      { tagName:'Login', lang:1, text:'Войти'},
      { tagName:'Login', lang:2, text:'Війти'},
      { tagName:'Login', lang:3, text:'Sign in'},
      { tagName:'NoAccount', lang:1, text:'Нет аккаунта'},
      { tagName:'NoAccount', lang:2, text:'Відсутній акаунт'},
      { tagName:'NoAccount', lang:3, text:'Don\'t have account'},
      { tagName:'SignUp', lang:1, text:'Зарегистрироваться'},
      { tagName:'SignUp', lang:2, text:'Зареєструватись'},
      { tagName:'SignUp', lang:3, text:'Sign up'},
    ];

    this._mockLocalizationStore['ManagePlacesMenuPage'] = [
      { tagName:'SelectShipAddress', lang:1, text:'Адреса доставки'},
      { tagName:'SelectShipAddress', lang:2, text:'Адреси доставки'},
      { tagName:'SelectShipAddress', lang:3, text:'Shipping addresses'},
      { tagName:'FavoriteStores', lang:1, text:'Избранные магазины'},
      { tagName:'FavoriteStores', lang:2, text:'Обрані крамниці'},
      { tagName:'FavoriteStores', lang:3, text:'Favorite stores'},
    ];

    this._mockLocalizationStore['MapPage'] = [
      { tagName:'Open', lang:1, text:'Открыто'},
      { tagName:'Open', lang:2, text:'Відчинено'},
      { tagName:'Open', lang:3, text:'Open'},
      { tagName:'Closed', lang:1, text:'Закрыто'},
      { tagName:'Closed', lang:2, text:'Зачинено'},
      { tagName:'Closed', lang:3, text:'Closed'},
      { tagName:'OpenHours', lang:1, text:'Время работы'},
      { tagName:'OpenHours', lang:2, text:'Години роботи'},
      { tagName:'OpenHours', lang:3, text:'Open hours'},
      { tagName:'Reviews', lang:1, text:'Отзывы'},
      { tagName:'Reviews', lang:2, text:'Відгуки'},
      { tagName:'Reviews', lang:3, text:'Reviews'},
      { tagName:'WriteReview', lang:1, text:'Оставить отзыв'},
      { tagName:'WriteReview', lang:2, text:'Залишити відгук'},
      { tagName:'WriteReview', lang:3, text:'Write a review'},
      { tagName:'toFav', lang:1, text:'В избранное'},
      { tagName:'toFav', lang:2, text:'У відбірне'},
      { tagName:'toFav', lang:3, text:'To favorite'},
      { tagName:'inNav', lang:1, text:'В навигаторе'},
      { tagName:'inNav', lang:2, text:'У навігаторі'},
      { tagName:'inNav', lang:3, text:'Navigate'},
      { tagName:'route', lang:1, text:'Маршрут'},
      { tagName:'route', lang:2, text:'Маршрут'},
      { tagName:'route', lang:3, text:'Route'},
      { tagName:'City', lang:1, text:'Город'},
      { tagName:'City', lang:2, text:'Місто'},
      { tagName:'City', lang:3, text:'City'},
      { tagName:'Address', lang:1, text:'Адрес'},
      { tagName:'Address', lang:2, text:'Адреса'},
      { tagName:'Address', lang:3, text:'Address'},
    ];

    this._mockLocalizationStore['NoveltyPage'] = [
      { tagName:'ToastMessage', lang:1, text:'Что-то пошло не так. Возможно товара уже нет в наличии'},
      { tagName:'ToastMessage', lang:2, text:'Щось пішло не так. Можливо товару вже немає в наявності'},
      { tagName:'ToastMessage', lang:3, text:'Something went wrong. Maybe the item is no longer in stock'},
    ];

    this._mockLocalizationStore['OrderDetailsPage'] = [
      { tagName:'ViewOrderDetails', lang:1, text:'Просмотр деталей заказа'},
      { tagName:'ViewOrderDetails', lang:2, text:'Перегляд деталей замовлення'},
      { tagName:'ViewOrderDetails', lang:3, text:'View order details'},
      { tagName:'OrderDate', lang:1, text:'Дата заказа'},
      { tagName:'OrderDate', lang:2, text:'Дата замовлення'},
      { tagName:'OrderDate', lang:3, text:'Order date'},
      { tagName:'OrderNumber', lang:1, text:'№ заказа'},
      { tagName:'OrderNumber', lang:2, text:'№ замовлення'},
      { tagName:'OrderNumber', lang:3, text:'Order #'},
      { tagName:'OrderTotal', lang:1, text:'Сумма заказа'},
      { tagName:'OrderTotal', lang:2, text:'Сума замовлення'},
      { tagName:'OrderTotal', lang:3, text:'Order total'},
      { tagName:'Items', lang:1, text:'товар(-а/-ов)'},
      { tagName:'Items', lang:2, text:'товар(-и/-ів)'},
      { tagName:'Items', lang:3, text:'item(s)'},
      { tagName:'ShipmentDetails', lang:1, text:'Детали доставки'},
      { tagName:'ShipmentDetails', lang:2, text:'Деталі доставки'},
      { tagName:'ShipmentDetails', lang:3, text:'Shipment details'},
      { tagName:'Shipment', lang:1, text:'Посылка'},
      { tagName:'Shipment', lang:2, text:'Посилка'},
      { tagName:'Shipment', lang:3, text:'Shipment'},
      { tagName:'Of', lang:1, text:'из'},
      { tagName:'Of', lang:2, text:'з'},
      { tagName:'Of', lang:3, text:'of'},
      { tagName:'Shipped', lang:1, text:'Доставлено'},
      { tagName:'Shipped', lang:2, text:'Доставлено'},
      { tagName:'Shipped', lang:3, text:'Shipped'},
      { tagName:'EstDeliveryDate', lang:1, text:'Предполагаемая дата доставки'},
      { tagName:'EstDeliveryDate', lang:2, text:'Передбачувана дата доставки'},
      { tagName:'EstDeliveryDate', lang:3, text:'Est. delivery date'},
      { tagName:'Qty', lang:1, text:'Кол-во'},
      { tagName:'Qty', lang:2, text:'Кіл-ть'},
      { tagName:'Qty', lang:3, text:'Qty'},
      { tagName:'SoldBy', lang:1, text:'Продавец'},
      { tagName:'SoldBy', lang:2, text:'Продавець'},
      { tagName:'SoldBy', lang:3, text:'Sold by'},
      { tagName:'PaymentInfo', lang:1, text:'Информация об оплате'},
      { tagName:'PaymentInfo', lang:2, text:'Інформація про оплату'},
      { tagName:'PaymentInfo', lang:3, text:'Payment information'},
      { tagName:'PaymentMethod', lang:1, text:'Способ оплаты'},
      { tagName:'PaymentMethod', lang:2, text:'Спосіб оплати'},
      { tagName:'PaymentMethod', lang:3, text:'Payment method'},
      { tagName:'ShippingAddress', lang:1, text:'Адрес доставки'},
      { tagName:'ShippingAddress', lang:2, text:'Адреса доставки'},
      { tagName:'ShippingAddress', lang:3, text:'Shipping address'},
      { tagName:'OrderSummary', lang:1, text:'Итог заказа'},
      { tagName:'OrderSummary', lang:2, text:'Підсумок замовлення'},
      { tagName:'OrderSummary', lang:3, text:'Order summary'},
      { tagName:'Items', lang:1, text:'Товары'},
      { tagName:'Items', lang:2, text:'Товари'},
      { tagName:'Items', lang:3, text:'Items'},
      { tagName:'Shipping', lang:1, text:'Доставка'},
      { tagName:'Shipping', lang:2, text:'Доставка'},
      { tagName:'Shipping', lang:3, text:'Shipping'},
      { tagName:'BonusesPaid', lang:1, text:'Использованные бонусы'},
      { tagName:'BonusesPaid', lang:2, text:'Використані бонуси'},
      { tagName:'BonusesPaid', lang:3, text:'Bonuses paid'},
      { tagName:'PromoBonusesPaid', lang:1, text:'Использованные акционные бонусы'},
      { tagName:'PromoBonusesPaid', lang:2, text:'Використані акційні бонуси'},
      { tagName:'PromoBonusesPaid', lang:3, text:'Promo bonuses paid'},
      { tagName:'PromocodeDiscount', lang:1, text:'Скидка промокода'},
      { tagName:'PromocodeDiscount', lang:2, text:'Знижка промокоду'},
      { tagName:'PromocodeDiscount', lang:3, text:'Promocode discount'},
      { tagName:'BonusesEarned', lang:1, text:'Полученные бонусы'},
      { tagName:'BonusesEarned', lang:2, text:'Отримані бонуси'},
      { tagName:'BonusesEarned', lang:3, text:'Bonuses earned'},
    ];

    this._mockLocalizationStore['PaymentPage'] = [
      { tagName:'ToHomePage', lang:1, text:'На главную'},
      { tagName:'ToHomePage', lang:2, text:'На головну'},
      { tagName:'ToHomePage', lang:3, text:'To home page'},
      { tagName:'NotSuccessful', lang:1, text:'К сожалению, оплата Вашего заказа не прошла успешно'},
      { tagName:'NotSuccessful', lang:2, text:'Нажаль, оплата Вашого замовлення не пройшла успішно'},
      { tagName:'NotSuccessful', lang:3, text:'Unfortunately, Your purchase has not ended successfully'},
      { tagName:'WithError', lang:1, text:'К сожалению, возникла ошибка во время оплаты Вашего заказа'},
      { tagName:'WithError', lang:2, text:'Нажаль, виникла помилка під час оплати Вашого замовлення'},
      { tagName:'WithError', lang:3, text:'Unfortunately, Your purchase has ended with error'},
      { tagName:'Successful', lang:1, text:'Оплата прошла успешно. Заказ отправлен в обработку'},
      { tagName:'Successful', lang:2, text:'Оплата пройшла успішно. Замовлення відправлено на опрацювання'},
      { tagName:'Successful', lang:3, text:'Payment was successful. Order sent for processing '},
    ];

    this._mockLocalizationStore['PollPage'] = [
      { tagName:'YourVariant', lang:1, text:'Ваш вариант'},
      { tagName:'YourVariant', lang:2, text:'Ваш варіант'},
      { tagName:'YourVariant', lang:3, text:'Your variant'},
      { tagName:'OwnVariant', lang:1, text:'Свой вариант'},
      { tagName:'OwnVariant', lang:2, text:'Свій варіант'},
      { tagName:'OwnVariant', lang:3, text:'Own variant'},
      { tagName:'Submit', lang:1, text:'Отправить'},
      { tagName:'Submit', lang:2, text:'Відправити'},
      { tagName:'Submit', lang:3, text:'Submit'},
      { tagName:'AlertMessage', lang:1, text:'Спасибо за участие! Ваше мнение важно для нас'},
      { tagName:'AlertMessage', lang:2, text:'Дякуємо за участь! Ваша думка важлива для нас'},
      { tagName:'AlertMessage', lang:3, text:'Thank you for taking a part! Your opinion is important to us'},
    ];

    this._mockLocalizationStore['RegisterPage'] = [
      { tagName:'RequiredField', lang:1, text:'Обязательное поле'},
      { tagName:'RequiredField', lang:2, text:'Обов\'язкове поле'},
      { tagName:'RequiredField', lang:3, text:'Required field'},
      { tagName:'WrongEMailFormat', lang:1, text:'Не правильный формат email адреса'},
      { tagName:'WrongEMailFormat', lang:2, text:'Не вірний формат email адреси'},
      { tagName:'WrongEMailFormat', lang:3, text:'Wrong email address format'},
      { tagName:'LengthNLT6', lang:1, text:'Значение должно быть не менее 6-ти символов'},
      { tagName:'LengthNLT6', lang:2, text:'Значення повинно бути не менше 6-ти символів'},
      { tagName:'LengthNLT6', lang:3, text:'Value length shouldn\'t be less than 6 symbols'},
      { tagName:'LengthNGT20', lang:1, text:'Значение должно быть не более 20-ти символов'},
      { tagName:'LengthNGT20', lang:2, text:'Значення повинно бути не більше 20-ти символів'},
      { tagName:'LengthNGT20', lang:3, text:'Value length shouldn\'t be grater than 20 symbols'},
      { tagName:'LengthNGT128', lang:1, text:'Значение должно быть не более 128-и символов'},
      { tagName:'LengthNGT128', lang:2, text:'Значення повинно бути не більше 128-и символів'},
      { tagName:'LengthNGT128', lang:3, text:'Value length shouldn\'t be grater than 128 symbols'},
      { tagName:'Email', lang:1, text:'Электронная почта'},
      { tagName:'Email', lang:2, text:'Електронна пошта'},
      { tagName:'Email', lang:3, text:'Email'},
      { tagName:'Password', lang:1, text:'Пароль'},
      { tagName:'Password', lang:2, text:'Пароль'},
      { tagName:'Password', lang:3, text:'Password'},
      { tagName:'Name', lang:1, text:'Имя'},
      { tagName:'Name', lang:2, text:'Ім\'я'},
      { tagName:'Name', lang:3, text:'Name'},
      { tagName:'Currency', lang:1, text:'Валюта'},
      { tagName:'Currency', lang:2, text:'Валюта'},
      { tagName:'Currency', lang:3, text:'Currency'},
      { tagName:'Localization', lang:1, text:'Локализация'},
      { tagName:'Localization', lang:2, text:'Локалізація'},
      { tagName:'Localization', lang:3, text:'Localization'},
      { tagName:'Cancel', lang:1, text:'Отменить'},
      { tagName:'Cancel', lang:2, text:'Відмінити'},
      { tagName:'Cancel', lang:3, text:'Cancel'},
      { tagName:'Chose', lang:1, text:'Выбрать'},
      { tagName:'Chose', lang:2, text:'Обрати'},
      { tagName:'Chose', lang:3, text:'Chose'},
      { tagName:'CreateAccount', lang:1, text:'Создать аккаунт'},
      { tagName:'CreateAccount', lang:2, text:'Створити акаунт'},
      { tagName:'CreateAccount', lang:3, text:'Create account'},
      { tagName:'HaveAccount', lang:1, text:'Уже имеете аккаунт'},
      { tagName:'HaveAccount', lang:2, text:'Вже маєте акаунт'},
      { tagName:'HaveAccount', lang:3, text:'Already have an account'},
      { tagName:'Login', lang:1, text:'Войти'},
      { tagName:'Login', lang:2, text:'Війти'},
      { tagName:'Login', lang:3, text:'Sign in'},
    ];

    this._mockLocalizationStore['SelectPmtMethodPage'] = [
      { tagName:'SelectPmtMethod', lang:1, text:'Выберите способ оплаты'},
      { tagName:'SelectPmtMethod', lang:2, text:'Оберіть спосіб оплати'},
      { tagName:'SelectPmtMethod', lang:3, text:'Select a payment method'},
      { tagName:'SelectLoan', lang:1, text:'Выберите кредит'},
      { tagName:'SelectLoan', lang:2, text:'Оберіть кредит'},
      { tagName:'SelectLoan', lang:3, text:'Select a loan'},
      { tagName:'LastName', lang:1, text:'Фамилия'},
      { tagName:'LastName', lang:2, text:'Прізвище'},
      { tagName:'LastName', lang:3, text:'Last name'},
      { tagName:'EnterLastName', lang:1, text:'Пожалуйста, введите свою фамилию'},
      { tagName:'EnterLastName', lang:2, text:'Будь-ласка, введіть своє прізвище'},
      { tagName:'EnterLastName', lang:3, text:'Please, enter your last name'},
      { tagName:'OnlyAlphabets', lang:1, text:'Допустимы только буквы'},
      { tagName:'OnlyAlphabets', lang:2, text:'Дозволені лише літери'},
      { tagName:'OnlyAlphabets', lang:3, text:'Only alphabets allowed'},
      { tagName:'FirstName', lang:1, text:'Имя'},
      { tagName:'FirstName', lang:2, text:'Ім\'я'},
      { tagName:'FirstName', lang:3, text:'First name'},
      { tagName:'EnterFirstName', lang:1, text:'Пожалуйста, введите своё имя'},
      { tagName:'EnterFirstName', lang:2, text:'Будь-ласка, введіть своє ім\'я'},
      { tagName:'EnterFirstName', lang:3, text:'Please, enter your first name'},
      { tagName:'MiddleName', lang:1, text:'По отчеству'},
      { tagName:'MiddleName', lang:2, text:'По батькові'},
      { tagName:'MiddleName', lang:3, text:'Middle name'},
      { tagName:'EnterMiddleName', lang:1, text:'Пожалуйста, введите своё имя по отчеству'},
      { tagName:'EnterMiddleName', lang:2, text:'Будь-ласка, введіть своє ім\'я по батькові'},
      { tagName:'EnterMiddleName', lang:3, text:'Please, enter your middle name'},
      { tagName:'PassportSerAndNum', lang:1, text:'Серия и номер паспорта'},
      { tagName:'PassportSerAndNum', lang:2, text:'Серія та номер паспорту'},
      { tagName:'PassportSerAndNum', lang:3, text:'Passport series and number'},
      { tagName:'EnterPassportSer', lang:1, text:'Пожалуйста, введите серию паспорта'},
      { tagName:'EnterPassportSer', lang:2, text:'Будь-ласка, введіть серію паспорту'},
      { tagName:'EnterPassportSer', lang:3, text:'Please, enter passport series'},
      { tagName:'EnterPassportNum', lang:1, text:'Пожалуйста, введите номер паспорта'},
      { tagName:'EnterPassportNum', lang:2, text:'Будь-ласка, введіть номер паспорту'},
      { tagName:'EnterPassportNum', lang:3, text:'Please, enter passport number'},
      { tagName:'Only2UL', lang:1, text:'Только 2 большие буквы разрешены'},
      { tagName:'Only2UL', lang:2, text:'Лише 2 великі літери дозволені'},
      { tagName:'Only2UL', lang:3, text:'Only 2 uppercase alphabets allowed'},
      { tagName:'Only6D', lang:1, text:'Только 6 цифер разрешены'},
      { tagName:'Only6D', lang:2, text:'Лише 6 цифер дозволені'},
      { tagName:'Only6D', lang:3, text:'Only 6 digits allowed'},
      { tagName:'ShouldBe6D', lang:1, text:'Номер паспорта должен состоять из 6 цифер'},
      { tagName:'ShouldBe6D', lang:2, text:'Номер паспорту повинен складатись із 6 цифер'},
      { tagName:'ShouldBe6D', lang:3, text:'Passport number should be 6 digits'},
      { tagName:'IssuedAuthority', lang:1, text:'Выдавший орган'},
      { tagName:'IssuedAuthority', lang:2, text:'Орган, що видав'},
      { tagName:'IssuedAuthority', lang:3, text:'Issued Authority'},
      { tagName:'EnterIssuedAuthority', lang:1, text:'Пожалуйста, введите выдавший орган'},
      { tagName:'EnterIssuedAuthority', lang:2, text:'Будь-ласка, введіть орган, що видав'},
      { tagName:'EnterIssuedAuthority', lang:3, text:'Please, enter issued authority'},
      { tagName:'TaxNumber', lang:1, text:'Идентификационный номер'},
      { tagName:'TaxNumber', lang:2, text:'Ідетифікаційний номер'},
      { tagName:'TaxNumber', lang:3, text:'Tax Number'},
      { tagName:'EnterTaxNumber', lang:1, text:'Пожалуйста, введите идентификационный номер'},
      { tagName:'EnterTaxNumber', lang:2, text:'Будь-ласка, введіть ідетифікаційний номер'},
      { tagName:'EnterTaxNumber', lang:3, text:'Please, enter tax number'},
      { tagName:'Only10D', lang:1, text:'Только 10 цифер разрешены'},
      { tagName:'Only10D', lang:2, text:'Лише 10 цифер дозволені'},
      { tagName:'Only10D', lang:3, text:'Only 10 digits allowed'},
      { tagName:'ShouldBe10D', lang:1, text:'Идентификационный номер должен состоять из 10 цифер'},
      { tagName:'ShouldBe10D', lang:2, text:'Ідетифікаційний номер повинен складатись із 10 цифер'},
      { tagName:'ShouldBe10D', lang:3, text:'Tax number should be 10 digits'},
      { tagName:'BirthDate', lang:1, text:'Дата рождения'},
      { tagName:'BirthDate', lang:2, text:'Дата народження'},
      { tagName:'BirthDate', lang:3, text:'Birth date'},
      { tagName:'EnterBirthDate', lang:1, text:'Пожалуйста, введите дату рождения'},
      { tagName:'EnterBirthDate', lang:2, text:'Будь-ласка, введіть дату народження'},
      { tagName:'EnterBirthDate', lang:3, text:'Please, enter your birth date'},
      { tagName:'Continue', lang:1, text:'Далее'},
      { tagName:'Continue', lang:2, text:'Далі'},
      { tagName:'Continue', lang:3, text:'Continue'},
    ];

    this._mockLocalizationStore['SelectShipAddressPage'] = [
      { tagName:'SelectShippingAddress', lang:1, text:'Выберите адрес доставки'},
      { tagName:'SelectShippingAddress', lang:2, text:'Оберіть адресу доставки'},
      { tagName:'SelectShippingAddress', lang:3, text:'Select a shipping address'},
      { tagName:'AddNewShippingAddress', lang:1, text:'Добавить новый адрес доставки'},
      { tagName:'AddNewShippingAddress', lang:2, text:'Додати нову адресу доставки'},
      { tagName:'AddNewShippingAddress', lang:3, text:'Add a New Shipping Address'},
    ];

    this._mockLocalizationStore['ShippingOptionsPage'] = [
      { tagName:'LoadingContent', lang:1, text:'Пожалуйста, подождите...'},
      { tagName:'LoadingContent', lang:2, text:'Будь-ласка, зачекайте...'},
      { tagName:'LoadingContent', lang:3, text:'Please, wait...'},
      { tagName:'ChooseShippingOptions', lang:1, text:'Выберите доставку'},
      { tagName:'ChooseShippingOptions', lang:2, text:'Оберіть доставку'},
      { tagName:'ChooseShippingOptions', lang:3, text:'Choose your shipping options'},
      { tagName:'ChooseDeliveryOption', lang:1, text:'Выберите вариант доставки'},
      { tagName:'ChooseDeliveryOption', lang:2, text:'Оберіть варіант доставки'},
      { tagName:'ChooseDeliveryOption', lang:3, text:'Choose a delivery option'},
      { tagName:'Shipment', lang:1, text:'Посылка'},
      { tagName:'Shipment', lang:2, text:'Посилка'},
      { tagName:'Shipment', lang:3, text:'Shipment'},
      { tagName:'Of', lang:1, text:'из'},
      { tagName:'Of', lang:2, text:'з'},
      { tagName:'Of', lang:3, text:'of'},
      { tagName:'GetIt', lang:1, text:'Получите'},
      { tagName:'GetIt', lang:2, text:'Отримайте'},
      { tagName:'GetIt', lang:3, text:'Get it'},
      { tagName:'DeliveryCost', lang:1, text:'Стоимость доставки'},
      { tagName:'DeliveryCost', lang:2, text:'Вартість доставки'},
      { tagName:'DeliveryCost', lang:3, text:'Delivery Cost'},
      { tagName:'FreeDelivery', lang:1, text:'БЕСПЛАТНАЯ доставка'},
      { tagName:'FreeDelivery', lang:2, text:'БЕЗКОШТОВНА доставка'},
      { tagName:'FreeDelivery', lang:3, text:'FREE delivery'},
      { tagName:'DeliveryBy', lang:1, text:'Доставляется'},
      { tagName:'DeliveryBy', lang:2, text:'Доставляється'},
      { tagName:'DeliveryBy', lang:3, text:'Delivery by'},
      { tagName:'Continue', lang:1, text:'Далее'},
      { tagName:'Continue', lang:2, text:'Далі'},
      { tagName:'Continue', lang:3, text:'Continue'},
    ];

    this._mockLocalizationStore['SupportPage'] = [
      { tagName:'SpecifyProblem', lang:1, text:'Укажите Ваше сообщение ниже'},
      { tagName:'SpecifyProblem', lang:2, text:'Вкажіть Ваше повідомлення нижче'},
      { tagName:'SpecifyProblem', lang:3, text:'Specify your problem below'},
      { tagName:'NoMessage', lang:1, text:'Вы не ввели сообщение'},
      { tagName:'NoMessage', lang:2, text:'Ви не ввели повідомлення'},
      { tagName:'NoMessage', lang:3, text:'You did not enter your message'},
      { tagName:'Submit', lang:1, text:'Отправить'},
      { tagName:'Submit', lang:2, text:'Відправити'},
      { tagName:'Submit', lang:3, text:'Submit'},
      { tagName:'ToastMessage', lang:1, text:'Ваша просьба о поддержке отправлена'},
      { tagName:'ToastMessage', lang:2, text:'Ваше прохання про підтримку відправлено'},
      { tagName:'ToastMessage', lang:3, text:'Your support request has been sent'},
    ];

    this._mockLocalizationStore['WarningViewPage'] = [
      { tagName:'Messages', lang:1, text:'Сообщения о товарах в Вашей корзине'},
      { tagName:'Messages', lang:2, text:'Повідомлення щодо товарів у Вашому кошику'},
      { tagName:'Messages', lang:3, text:'Messages for items in your cart'},
    ];

    this._mockLocalizationStore['OrdersPage'] = [
      { tagName:'YourOrders', lang:1, text:'Ваши заказы'},
      { tagName:'YourOrders', lang:2, text:'Ваші замовлення'},
      { tagName:'YourOrders', lang:3, text:'Your orders'},
      { tagName:'OrderedOn', lang:1, text:'Заказано'},
      { tagName:'OrderedOn', lang:2, text:'Замовлено'},
      { tagName:'OrderedOn', lang:3, text:'Ordered on'},
      { tagName:'BuyItAgain', lang:1, text:'Купить снова'},
      { tagName:'BuyItAgain', lang:2, text:'Купити знову'},
      { tagName:'BuyItAgain', lang:3, text:'Buy it again'},
      { tagName:'ViewOrderDetails', lang:1, text:'Посмотреть детали заказа'},
      { tagName:'ViewOrderDetails', lang:2, text:'Подивитись деталі замовлення'},
      { tagName:'ViewOrderDetails', lang:3, text:'View order details'},
      { tagName:'TrackItem', lang:1, text:'Отследить заказ'},
      { tagName:'TrackItem', lang:2, text:'Відстежити замовлення'},
      { tagName:'TrackItem', lang:3, text:'Track item'},
      { tagName:'WriteProductReview', lang:1, text:'Оставить отзыв о товаре'},
      { tagName:'WriteProductReview', lang:2, text:'Залишити відгук про товар'},
      { tagName:'WriteProductReview', lang:3, text:'Write a product review'},
      { tagName:'AlertMessage', lang:1, text:'К сожалению, этого товара сейчас нет в наличии'},
      { tagName:'AlertMessage', lang:2, text:'Нажаль, цього товару наразі немає в наявності'},
      { tagName:'AlertMessage', lang:3, text:'Unfortunately, this item is currently out of stock'},
    ];

    this._mockLocalizationStore['BonusComponent'] = [
      { tagName:'bonuses', lang:1, text:'бонусов'},
      { tagName:'bonuses', lang:2, text:'бонусів'},
      { tagName:'bonuses', lang:3, text:'bonuses'},
    ];

    this._mockLocalizationStore['BonusPayComponent'] = [
      { tagName:'CouldPayUpTo', lang:1, text:'Вы можете использовать'},
      { tagName:'CouldPayUpTo', lang:2, text:'Ви можете використати'},
      { tagName:'CouldPayUpTo', lang:3, text:'You could pay up to'},
      { tagName:'BonusesForThisPurchase', lang:1, text:'бонусов для этой покупки'},
      { tagName:'BonusesForThisPurchase', lang:2, text:'бонусів для цієї купівлі'},
      { tagName:'BonusesForThisPurchase', lang:3, text:'bonuses for this purchase'},
      { tagName:'TickPayBonuses', lang:1, text:'Выберите "Изпользовать акционные бонусы", если Вы хотите заплатить бонусами'},
      { tagName:'TickPayBonuses', lang:2, text:'Оберіть "Використати акційні бонуси", якщо Ви бажаєте сплатити бонусами'},
      { tagName:'TickPayBonuses', lang:3, text:'Tick "Pay promotional bonuses" option, if you want to pay promotional bonuses.'},
      { tagName:'PayBonuses', lang:1, text:'Изпользовать бонусы'},
      { tagName:'PayBonuses', lang:2, text:'Використати бонуси'},
      { tagName:'PayBonuses', lang:3, text:'Pay bonuses'},
      { tagName:'EnterBonusQuantity', lang:1, text:'Введите количество бонусов'},
      { tagName:'EnterBonusQuantity', lang:2, text:'Введіть кількість бонусів'},
      { tagName:'EnterBonusQuantity', lang:3, text:'Enter bonus quantity'},
      { tagName:'OnlyDigits', lang:1, text:'Допустимы только цифры'},
      { tagName:'OnlyDigits', lang:2, text:'Дозволені лише цифри'},
      { tagName:'OnlyDigits', lang:3, text:'Only digits allowed'},
      { tagName:'PayPromotionalBonuses', lang:1, text:'Изпользовать акционные бонусы'},
      { tagName:'PayPromotionalBonuses', lang:2, text:'Використати акційні бонуси'},
      { tagName:'PayPromotionalBonuses', lang:3, text:'Pay promotional bonuses'},
    ];

    this._mockLocalizationStore['CreditComponent'] = [
      { tagName:'MaxLoanPeriod', lang:1, text:'Максимальный срок кредита - до'},
      { tagName:'MaxLoanPeriod', lang:2, text:'Максимальний срок кредиту - до'},
      { tagName:'MaxLoanPeriod', lang:3, text:'Maximum loan period - up to'},
      { tagName:'months', lang:1, text:'месяцев'},
      { tagName:'months', lang:2, text:'місяців'},
      { tagName:'months', lang:3, text:'months'},
      { tagName:'GracePeriod', lang:1, text:'Льготный период'},
      { tagName:'GracePeriod', lang:2, text:'Пільговий період'},
      { tagName:'GracePeriod', lang:3, text:'Grace period'},
      { tagName:'FirstPayment', lang:1, text:'Первый взнос'},
      { tagName:'FirstPayment', lang:2, text:'Перший внесок'},
      { tagName:'FirstPayment', lang:3, text:'First payment'},
      { tagName:'MonthlyFee', lang:1, text:'Ежемесячная комиссия'},
      { tagName:'MonthlyFee', lang:2, text:'Щомісячна комісія'},
      { tagName:'MonthlyFee', lang:3, text:'Monthly fee'},
      { tagName:'AfterGracePeriod', lang:1, text:'после льготного периода'},
      { tagName:'AfterGracePeriod', lang:2, text:'після пільгового періоду'},
      { tagName:'AfterGracePeriod', lang:3, text:'after grace period'},
      { tagName:'OfLoanAmount', lang:1, text:'от суммы кредита'},
      { tagName:'OfLoanAmount', lang:2, text:'від суми кредиту'},
      { tagName:'OfLoanAmount', lang:3, text:'of the loan amount'},
      { tagName:'MaxLoanAmount', lang:1, text:'Максимальная сумма кредита'},
      { tagName:'MaxLoanAmount', lang:2, text:'Максимальна сума кредиту'},
      { tagName:'MaxLoanAmount', lang:3, text:'Maximum loan amount'},
      { tagName:'AnnualRate', lang:1, text:'Годовая % ставка'},
      { tagName:'AnnualRate', lang:2, text:'Річна % ставка'},
      { tagName:'AnnualRate', lang:3, text:'Annual % rate'},
      { tagName:'TermOfLoan', lang:1, text:'Срок кредита, мес'},
      { tagName:'TermOfLoan', lang:2, text:'Термін кредиту, міс'},
      { tagName:'TermOfLoan', lang:3, text:'Term of loan, months'},
      { tagName:'MonthsPopHeader', lang:1, text:'Месяцев'},
      { tagName:'MonthsPopHeader', lang:2, text:'Місяців'},
      { tagName:'MonthsPopHeader', lang:3, text:'Months'},
      { tagName:'MonthlyPayment', lang:1, text:'Ежемесячный платеж'},
      { tagName:'MonthlyPayment', lang:2, text:'Щомісячний платіж'},
      { tagName:'MonthlyPayment', lang:3, text:'Monthly payment'},
    ];

    this._mockLocalizationStore['CreditBriefComponent'] = [
      { tagName:'LoanPeriod', lang:1, text:'Период кредитования'},
      { tagName:'LoanPeriod', lang:2, text:'Період кредитування'},
      { tagName:'LoanPeriod', lang:3, text:'Loan period'},
      { tagName:'Months', lang:1, text:'месяцев'},
      { tagName:'Months', lang:2, text:'місяців'},
      { tagName:'Months', lang:3, text:'months'},
      { tagName:'MonthlyPayment', lang:1, text:'Ежемесячный платеж'},
      { tagName:'MonthlyPayment', lang:2, text:'Щомісячний платіж'},
      { tagName:'MonthlyPayment', lang:3, text:'Monthly payment'},
      { tagName:'ApproxCalculation', lang:1, text:'Расчёт ежемесячного платежа приблизительный. Окончательная сумма будет определена кредитным манеджером'},
      { tagName:'ApproxCalculation', lang:2, text:'Розрахунок щомісячного платежу приблизний. Кінцева сума буде визначена крединтим менеджером'},
      { tagName:'ApproxCalculation', lang:3, text:'The calculation of the monthly payment is approximate. The final value will be defined by the credit manager'},
    ];

    this._mockLocalizationStore['CustomPopupComponent'] = [
      { tagName:'SelectPickupPlace', lang:1, text:'Выберите пункт выдачи'},
      { tagName:'SelectPickupPlace', lang:2, text:'Оберіть пункт видачі'},
      { tagName:'SelectPickupPlace', lang:3, text:'Select pickup place'},
      { tagName:'AlertTitle', lang:1, text:'Подтверждение'},
      { tagName:'AlertTitle', lang:2, text:'Підтвердження'},
      { tagName:'AlertTitle', lang:3, text:'Confirmation'},
      { tagName:'AlertMessage', lang:1, text:'Вы действительно хотите выбрать этот пункт выдачи?'},
      { tagName:'AlertMessage', lang:2, text:'Ви дійсно бажаєте обрати цей пункт видачі?'},
      { tagName:'AlertMessage', lang:3, text:'Are you about to select this place to pickup from?'},
      { tagName:'Cancel', lang:1, text:'Отменить'},
      { tagName:'Cancel', lang:2, text:'Відмінити'},
      { tagName:'Cancel', lang:3, text:'Cancel'},
    ];

    this._mockLocalizationStore['DropdownListComponent'] = [
      { tagName:'Qty', lang:1, text:'Кол-во'},
      { tagName:'Qty', lang:2, text:'Кіл-ть'},
      { tagName:'Qty', lang:3, text:'Qty'},
    ];

    this._mockLocalizationStore['FilterComponent'] = [
      { tagName:'Items', lang:1, text:'товаров'},
      { tagName:'Items', lang:2, text:'товарів'},
      { tagName:'Items', lang:3, text:'items'},
      { tagName:'Filter', lang:1, text:'Фильтр'},
      { tagName:'Filter', lang:2, text:'Фільтр'},
      { tagName:'Filter', lang:3, text:'Filter'},
    ];

    this._mockLocalizationStore['ItemComponent'] = [
      { tagName:'OffersFrom', lang:1, text:'предложений от'},
      { tagName:'OffersFrom', lang:2, text:'пропозицій від'},
      { tagName:'OffersFrom', lang:3, text:'offers from'},
      { tagName:'InStock', lang:1, text:'В наличии'},
      { tagName:'InStock', lang:2, text:'В наявності'},
      { tagName:'InStock', lang:3, text:'In Stock'},
      { tagName:'SeeMoreChoices', lang:1, text:'Посмотреть другие варианты'},
      { tagName:'SeeMoreChoices', lang:2, text:'Переглянути інші варіанти'},
      { tagName:'SeeMoreChoices', lang:3, text:'In See more choices'},
    ];

    this._mockLocalizationStore['ItemPropsComponent'] = [
      { tagName:'FeaturesDetails', lang:1, text:'Особенности и Детали'},
      { tagName:'FeaturesDetails', lang:2, text:'Особливості та Деталі'},
      { tagName:'FeaturesDetails', lang:3, text:'Features & Details'},
    ];

    this._mockLocalizationStore['ItemReviewComponent'] = [
      { tagName:'by', lang:1, text:'от'},
      { tagName:'by', lang:2, text:'від'},
      { tagName:'by', lang:3, text:'by'},
      { tagName:'on', lang:1, text:''},
      { tagName:'on', lang:2, text:''},
      { tagName:'on', lang:3, text:'on'},
      { tagName:'Advantages', lang:1, text:'Преимущества'},
      { tagName:'Advantages', lang:2, text:'Переваги'},
      { tagName:'Advantages', lang:3, text:'Advantages'},
      { tagName:'Disadvantages', lang:1, text:'Недостатки'},
      { tagName:'Disadvantages', lang:2, text:'Недоліки'},
      { tagName:'Disadvantages', lang:3, text:'Disadvantages'},
      { tagName:'WasHelpful', lang:1, text:'Полезен ли был Вам этот отзыв'},
      { tagName:'WasHelpful', lang:2, text:'Чи цей відгук був корисним для Вас'},
      { tagName:'WasHelpful', lang:3, text:'Was this review helpful to you'},
      { tagName:'Helpful', lang:1, text:'Полезный'},
      { tagName:'Helpful', lang:2, text:'Корисний'},
      { tagName:'Helpful', lang:3, text:'Helpful'},
      { tagName:'NotHelpful', lang:1, text:'Не Полезный'},
      { tagName:'NotHelpful', lang:2, text:'Не Корисний'},
      { tagName:'NotHelpful', lang:3, text:'Not Helpful'},
      { tagName:'Thanks', lang:1, text:'Спасибо Вам за отзыв'},
      { tagName:'Thanks', lang:2, text:'Дякуємо Вам за відгук'},
      { tagName:'Thanks', lang:3, text:'Thank you for your feedback'},
      { tagName:'PeopleFound', lang:1, text:'людям это помогло'},
      { tagName:'PeopleFound', lang:2, text:'людям це допомогло'},
      { tagName:'PeopleFound', lang:3, text:'people found this helpful'},
      { tagName:'Answers', lang:1, text:'Ответы'},
      { tagName:'Answers', lang:2, text:'Відповіді'},
      { tagName:'Answers', lang:3, text:'Answers'},
    ];

    this._mockLocalizationStore['PromoCodeComponent'] = [
      { tagName:'PromoCode', lang:1, text:'Промокод'},
      { tagName:'PromoCode', lang:2, text:'Промокод'},
      { tagName:'PromoCode', lang:3, text:'Promotional Code'},
      { tagName:'EnterCode', lang:1, text:'Введите код'},
      { tagName:'EnterCode', lang:2, text:'Введіть код'},
      { tagName:'EnterCode', lang:3, text:'Enter code'},
      { tagName:'Apply', lang:1, text:'Применить'},
      { tagName:'Apply', lang:2, text:'Застосувати'},
      { tagName:'Apply', lang:3, text:'Apply'},
      { tagName:'ErrorText', lang:1, text:'Содержимое корзины было обновлено. Пожалуйста, примените промокод снова'},
      { tagName:'ErrorText', lang:2, text:'Вміст кошика було оновлено. Будь-ласка, застосуйте промокод знову'},
      { tagName:'ErrorText', lang:3, text:'Cart content has been updated. Please, apply promocode again'},
    ];

    this._mockLocalizationStore['ReadMoreComponent'] = [
      { tagName:'Read', lang:1, text:'Читать'},
      { tagName:'Read', lang:2, text:'Читати'},
      { tagName:'Read', lang:3, text:'Read'},
      { tagName:'More', lang:1, text:'больше'},
      { tagName:'More', lang:2, text:'більше'},
      { tagName:'More', lang:3, text:'more'},
      { tagName:'Less', lang:1, text:'меньше'},
      { tagName:'Less', lang:2, text:'менше'},
      { tagName:'Less', lang:3, text:'less'},
    ];

    this._mockLocalizationStore['SearchBtnComponent'] = [
      { tagName:'What', lang:1, text:'Что Вы ищете'},
      { tagName:'What', lang:2, text:'Що Ви шукаєте'},
      { tagName:'What', lang:3, text:'What are you looking for'},
    ];

    this._mockLocalizationStore['ShippingAddressComponent'] = [
      { tagName:'Phone', lang:1, text:'Телефон'},
      { tagName:'Phone', lang:2, text:'Телефон'},
      { tagName:'Phone', lang:3, text:'Phone'},
      { tagName:'DeliverToThis', lang:1, text:'Доставить по этому адресу'},
      { tagName:'DeliverToThis', lang:2, text:'Доставити за цією адресою'},
      { tagName:'DeliverToThis', lang:3, text:'Deliver to this address'},
      { tagName:'Edit', lang:1, text:'Редактировать'},
      { tagName:'Edit', lang:2, text:'Редагувати'},
      { tagName:'Edit', lang:3, text:'Edit'},
      { tagName:'Delete', lang:1, text:'Удалить'},
      { tagName:'Delete', lang:2, text:'Видалити'},
      { tagName:'Delete', lang:3, text:'Delete'},
      { tagName:'AlertTitle', lang:1, text:'Подтверждение'},
      { tagName:'AlertTitle', lang:2, text:'Підтвердження'},
      { tagName:'AlertTitle', lang:3, text:'Confirmation'},
      { tagName:'AlertMessage', lang:1, text:'Вы уверены, что хотите удалить этот адрес из своих избранных адресов?'},
      { tagName:'AlertMessage', lang:2, text:'Ви впевнені, що бажаєте видалити цю адресу зі своїх обраних адрес?'},
      { tagName:'AlertMessage', lang:3, text:'Are you sure you want to delete this address from your favorite addresses?'},
      { tagName:'Cancel', lang:1, text:'Отменить'},
      { tagName:'Cancel', lang:2, text:'Відмінити'},
      { tagName:'Cancel', lang:3, text:'Cancel'},
    ];

    this._mockLocalizationStore['CartService'] = [
      { tagName:'MaxLoan', lang:1, text:'Максимальный лимит кредита превышен'},
      { tagName:'MaxLoan', lang:2, text:'Максимальний кредитний ліміт перевищено'},
      { tagName:'MaxLoan', lang:3, text:'Max loan limit exceeded'},
      { tagName:'MinLoan', lang:1, text:'Сумма кредита ниже лимита'},
      { tagName:'MinLoan', lang:2, text:'Сума кредиту нижча за межу'},
      { tagName:'MinLoan', lang:3, text:'The loan amount is below limit'},
      { tagName:'AddedToCart', lang:1, text:'Товар добавлен в корзину'},
      { tagName:'AddedToCart', lang:2, text:'Товар додано до кошика'},
      { tagName:'AddedToCart', lang:3, text:'Item added to cart'},
      { tagName:'SomethingWrong', lang:1, text:'Что-то пошло не так'},
      { tagName:'SomethingWrong', lang:2, text:'Щось пішло не так'},
      { tagName:'SomethingWrong', lang:3, text:'Something went wrong'},
    ];

    this._mockLocalizationStore['UserService'] = [
      { tagName:'AlertTitle', lang:1, text:'Ошибка'},
      { tagName:'AlertTitle', lang:2, text:'Помилка'},
      { tagName:'AlertTitle', lang:3, text:'Sorry'},
      { tagName:'AlertMessage', lang:1, text:'Этот магазин уже есть в Ваших избранных'},
      { tagName:'AlertMessage', lang:2, text:'Ця крамниця вже є у Ваших обраних'},
      { tagName:'AlertMessage', lang:3, text:'You already have this address in favorites'},
      { tagName:'ToastMessage', lang:1, text:'Магазин добавлен в избранные'},
      { tagName:'ToastMessage', lang:2, text:'Крамницю додано до обраних'},
      { tagName:'ToastMessage', lang:3, text:'Store added to favorites'},
    ];
  }

  public getLocalization(data: { componentName: string, lang: number }): Promise<IDictionary<string>> {
    let mockResult: IDictionary<string> = {};
    let localeArray: ILocalization[] = this._mockLocalizationStore[data.componentName];
    if(localeArray) {
      localeArray = localeArray
        .filter((value) => {
          return value.lang === +data.lang;
        });
      localeArray.forEach((value) => mockResult[value.tagName] = value.text);
    }
    let promise = Promise.resolve(mockResult);
    return promise;
  }
}

interface ILocalization {
  tagName: string;
  lang: number;
  text: string
}
