import {IDictionary, Providers} from '../../../core/app-core';
import {AppParam} from '../../../model/app-param';
import IKeyedCollection = Providers.IKeyedCollection;
import {ProductReview} from '../../../model/product-review';
import {Supplier} from '../../../model/supplier';
import {Currency} from '../../../model/currency';
import {Lang} from '../../../model/lang';
import {QuotationProduct} from '../../../model/quotation-product';
import {ProductStorePlace} from '../../../model/product-store-place';
import {StorePlace} from '../../../model/store-place';
import {Quotation} from '../../../model/quotation';
import {Manufacturer} from '../../../model/manufacturer';
import {LoSupplEntity} from '../../../model/lo-suppl-entity';
import {LoEntity} from '../../../model/lo-entity';
import {LoTrackLog} from '../../../model/lo-track-log';
import {Shipment} from '../../../model/shipment';
import {Country} from '../../../model/country';
import {City} from '../../../model/city';
import {Region} from '../../../model/region';
import {Store} from '../../../model/store';
import {StoreReview} from '../../../model/store-review';
import {EnumPaymentMethod} from '../../../model/enum-payment-method';
import {Novelty} from '../../../model/novelty';
import {Poll} from '../../../model/poll';
import {PollQuestion} from '../../../model/poll-question';
import {PollQuestionAnswer} from '../../../model/poll-question-answer';
import {ClientPollAnswer} from '../../../model/client-poll-answer';
import {CreditProduct} from '../../../model/credit-product';
import {NoveltyDetails} from '../../../model/novelty-det';
import {DeviceData} from '../../../model/device-data';
import {Category} from '../../../model/category';
import {MeasureUnit} from '../../../model/measure-unit';
import {BannerSlide} from '../../../model/banner-slide';
import {ClientMessage} from '../../../model/client-message';
import {CurrencyRate} from '../../../model/currency-rate';
import {LoDeliveryType} from '../../../model/lo-delivery-type';
import {LoEntityOffice} from '../../../model/lo-entity-office';
import {News} from '../../../model/news';
import {NewsCategory} from '../../../model/news-category';
import {LoDeliveryTypeAttr} from '../../../model/lo-delivery-type-attr';

export abstract class AbstractGeoRepository {
  public async abstract loadCityCache();
  public async abstract getCityById(id: number): Promise<City>;
  public async abstract getCities(): Promise<City[]>;
  public async abstract searchCities(srchString: string): Promise<City[]>;
  public async abstract loadRegionsCache();
  public async abstract getRegionById(id: number): Promise<Region>;
  public async abstract getRegions(): Promise<Region[]>;
  public async abstract getCitiesWithStores(): Promise<City[]>;
  public async abstract getCountryById(id: number): Promise<Country>;
  public async abstract getCountries(): Promise<Country[]>;
}
